server:
  port: 9090

spring:
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8080
          predicates:
            - Path=/order/api/v1/**
          filters:
            - LoggingFilter=

        - id: payment
          uri: http://localhost:8081
          predicates:
            - Path=/payment/api/v1/**
          filters:
            - LoggingFilter=

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka